# Site settings
author: Wendy
title: Snakes & Bears
header-img: img/home-bg.png
email: jwendyjiang@gmail.com
copyright_name: Wendy
description: > # this means to ignore newlines until "baseurl:"
  Continuous Learning: Trials, Takeaways, Thoughts
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jwendyjiang

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
